-- ============================================================
-- ⚠️ 将来用・まだ実行しないでください（ファイル名に .FUTURE を付与）
-- ============================================================
-- Style の「Face（文字盤）」コンポーネントを保存するための追加列。
-- すべて nullable な ADD COLUMN のみ＝既存データ・既存挙動を壊さない非破壊変更。
-- UI（StyleSpec / ReproduceStyle）は、これらの列が無くても成立するように作ってある。
-- Face を本格稼働させる準備ができたら、このSQLを Supabase SQL Editor で実行し、
-- 同時に投稿フォーム（PostForm）に Face 入力を追加し、posts の SELECT 列に追記する。
--
-- 文字盤は「Apple の文字盤共有リンク」または「設定レシピ(jsonb)」として保持する。
-- ============================================================

-- alter table public.posts
--   add column if not exists face_share_url text,   -- Apple Watch 文字盤の共有リンク
--   add column if not exists face_name text,        -- 文字盤名（例：メリディアン / インフォグラフ）
--   add column if not exists face_recipe jsonb;     -- コンプリケーション等の設定レシピ
--
-- comment on column public.posts.face_share_url is 'Apple Watch face shared link';
-- comment on column public.posts.face_name      is 'Watch face display name';
-- comment on column public.posts.face_recipe    is 'Face setup recipe (complications, color, etc.)';
